// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7_5UnWtfAMLuwcYTYtkTZCSKJoVdIUc',
    appId: '1:977725648768:web:230bf8255db59c049a9b65',
    messagingSenderId: '977725648768',
    projectId: 'ip-project-88b89',
    authDomain: 'ip-project-88b89.firebaseapp.com',
    storageBucket: 'ip-project-88b89.firebasestorage.app',
    measurementId: 'G-P4P1VTKQKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2etJCKDUNEmmmx7DUQwQHro4A7lMYjM',
    appId: '1:977725648768:android:76ff53b07c07c1749a9b65',
    messagingSenderId: '977725648768',
    projectId: 'ip-project-88b89',
    storageBucket: 'ip-project-88b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHAy1VJ6ewIMblXI6Nlx3nENpV53JkpA',
    appId: '1:977725648768:ios:632566c82683a0649a9b65',
    messagingSenderId: '977725648768',
    projectId: 'ip-project-88b89',
    storageBucket: 'ip-project-88b89.firebasestorage.app',
    iosBundleId: 'com.example.speedBreakAlert1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHAy1VJ6ewIMblXI6Nlx3nENpV53JkpA',
    appId: '1:977725648768:ios:632566c82683a0649a9b65',
    messagingSenderId: '977725648768',
    projectId: 'ip-project-88b89',
    storageBucket: 'ip-project-88b89.firebasestorage.app',
    iosBundleId: 'com.example.speedBreakAlert1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_7_5UnWtfAMLuwcYTYtkTZCSKJoVdIUc',
    appId: '1:977725648768:web:152234912441a93c9a9b65',
    messagingSenderId: '977725648768',
    projectId: 'ip-project-88b89',
    authDomain: 'ip-project-88b89.firebaseapp.com',
    storageBucket: 'ip-project-88b89.firebasestorage.app',
    measurementId: 'G-JRFQ08GT8R',
  );
}
